server:
  port: 4444

spring:
  application:
    name: homelibrary-app
  datasource:
    url: jdbc:postgresql://localhost:4445/booksbase
    username: owner
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop